### PR TITLE
change to java version 11

### PR DESCRIPTION
**Pull request by IvoStaynov**
@NewestUser for review

### CODE REVIEW

**Review by NewestUser — COMMENTED** [review]
Please update the Readme by adding the `. /`

**Review by NewestUser — APPROVED** [review]
LGTM

**Comment by NewestUser** [comment]
@IvoStaynov when merging please select from the drop down `Squash and merge`

**Review by rositsabodurova — APPROVED** [review]
LGTM

**Comment by NewestUser** [comment]
@IvoStaynov Please merge your PRs

**Pull request merged**
